name: Matrix Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dev
      - wip

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Golang ${{ matrix.go }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.25"
          - "1.18"

    steps:
      - uses: actions/checkout@v5
      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - uses: extractions/setup-crate@v1
        with:
          repo: casey/just
      - name: Test option
        run: just test option
      - name: Test result
        run: just test result
      - name: Test bench
        run: just bench
